### ISSUE TITLE
"GTSAM exception caught:  Indeterminant linear system detected while working near variable" then crash

### ISSUE THREAD

**Issue by ApoloM** [introlab/rtabmap_ros#1057]
Hi everyone, I'm working in a project with ROS1 in which we use Rtabmap for localization in a previously mapped environment. I'm using the localization_pose to feed my localization stack.  Recently I have experienced problems with GTSAM which warns for "inderteminant linear systems". Eventually, it also crashes with the following FATAL ERROR.

```
FATAL] (2023-10-27 09:25:31.539) Transform.cpp:184::inverse() Condition (invertible) not met! [This transform is not invertible! xyz=inf,inf,0.000000 rpy=0.000000,0.000000,-1.267575 
[0.298596 0.954380 0.000000 inf;
 -0.954380 0.298596 -0.000000 inf;
 -0.000000 0.000000 1.000000 0.000000;
 0 0 0 1]]
terminate called after throwing an instance of 'UException'
  what():  [FATAL] (2023-10-27 09:25:31.539) Transform.cpp:184::inverse() Condition (invertible) not met! [This transform is not invertible! xyz=inf,inf,0.000000 rpy=0.000000,0.000000,-1.267575 
[0.298596 0.954380 0.000000 inf;
 -0.954380 0.298596 -0.000000 inf;
 -0.000000 0.000000 1.000000 0.000000;
 0 0 0 1]]
```

By setting the  "--udebug --logconsole" arguments I was able to see some information about the problem. However something very strange took my attemption, which are the following debug messages:

```
[DEBUG] (2023-10-27 09:25:31.535) Rtabmap.cpp:2946::process() Constraint -8->-8 (type=PosePrior)
[DEBUG] (2023-10-27 09:25:31.535) Rtabmap.cpp:2948::process() Constraint 1058->-8 (type=Landmark, var = 0.001000 0.010000)
[DEBUG] (2023-10-27 09:25:31.535) Rtabmap.cpp:2946::process() Constraint 875->875 (type=PosePrior)
[DEBUG] (2023-10-27 09:25:31.535) Rtabmap.cpp:2948::process() Constraint 1058->875 (type=LocalSpaceClosure, var = 0.000003 0.002736)
[DEBUG] (2023-10-27 09:25:31.535) Rtabmap.cpp:2946::process() Constraint 876->876 (type=PosePrior)
[DEBUG] (2023-10-27 09:25:31.535) Rtabmap.cpp:2948::process() Constraint 1058->876 (type=GlobalClosure, var = 0.000002 0.001697)
[DEBUG] (2023-10-27 09:25:31.535) Rtabmap.cpp:2946::process() Constraint 1033->1033 (type=PosePrior)
[DEBUG] (2023-10-27 09:25:31.535) Rtabmap.cpp:2948::process() Constraint 1058->1033 (type=LocalSpaceClosure, var = 0.000027 0.007702)
[DEBUG] (2023-10-27 09:25:31.535) Rtabmap.cpp:2952::process() Pose -8 xyz=0.851523,-0.041897,0.404141 rpy=0.085773,0.006991,1.561444
[DEBUG] (2023-10-27 09:25:31.535) Rtabmap.cpp:2952::process() Pose 875 xyz=0.319759,-0.040769,0.000000 rpy=0.000000,-0.000000,0.013201
[DEBUG] (2023-10-27 09:25:31.536) Rtabmap.cpp:2952::process() Pose 876 xyz=0.297985,-0.013632,0.000000 rpy=0.000000,0.000000,-0.039805
[DEBUG] (2023-10-27 09:25:31.536) Rtabmap.cpp:2952::process() Pose 1033 xyz=0.240514,-0.004088,0.000000 rpy=0.000000,-0.000000,0.023084
[DEBUG] (2023-10-27 09:25:31.536) Rtabmap.cpp:2952::process() Pose 1058 xyz=-197.406799,29.594700,0.000000 rpy=0.000000,0.000000,-3.107898
```

The above logs, show the constraints used in the optmization. However the last line took my attemption. In the referred line we can see that the pose of the node 1058 is very distant (in terms of xyz) from the other nodes of the graph. Then, I was looking in the code and found these debug messages in the Rtabmap library. I noticed that the odom pose is not being transformed to the same frame of the graph nodes before optimization, as shown in the following lines:

https://github.com/introlab/rtabmap_ros/blob/3293f2b51a42cdcd4f531576e3d787f149ac2e1b/rtabmap_slam/src/CoreWrapper.cpp#L2026C6-L2030

Based in my knowledge of optimization, I thought it would be better for the optimization problem (in terms of speed and accuracy) if the initial guess was near to the minimum. I understand that the mapCorrection output is being used to generate the mapToOdom information. However, in my point of view, it would be better for the optimization problem, if the odom pose was transformed  to the map frame with the last map->odom transform before passing it to the optimizer. Then the mapCorrection output could be used to correct the last map->odom TF from /tf.

I would appreciate any comments and clarifications on this.
Thank you!

**Comment by matlabbe** [comment]
It seems you are using rtabmap 0.20.18:
https://github.com/introlab/rtabmap/blob/4d8c1d8b90afc796bf3a3747516d68dd0e072409/corelib/src/Rtabmap.cpp#L2938-L2953

In that code, the poses fed to optimization are taken for `_optimizedPoses` map. The `_optimizedPoses` map should contain the latest pose already corrected by `_mapCorrection` before the graph optimization: https://github.com/introlab/rtabmap/blob/4d8c1d8b90afc796bf3a3747516d68dd0e072409/corelib/src/Rtabmap.cpp#L1538, which would mean that the large jump is coming from the odometry.

For the `Transform.cpp:184::inverse()` error, does it appear before or after optimization? I fixed a [similar error some time ago](https://github.com/introlab/rtabmap/commit/ae3fda37a90eccf99c76227bd59a4112158b6c0d), not sure it is the same. You may try latest master version.

**Comment by matlabbe** [comment]
For the `inverse()` error, that [commit](https://github.com/introlab/rtabmap/commit/ae3fda37a90eccf99c76227bd59a4112158b6c0d) should fix that. The `Indeterminant linear system detected while working near variable` would still happen though, but at least rtabmap won't crash and only reject the localization. For GTSAM error, I would need to make some tests by artificially use large odometry values and see if I can reproduce the same error. I also saw this GTSAM error when the scale of the sensor changed (e..g, switching a camera to a new one with wrong calibration), make it difficult for the optimizer to correctly converge to a solution.

**Comment by ApoloM** [comment]
Hi, thanks for the response.
I tried adding this commit to the version 0.20.18 as a patch. However, it still crashing, as shown below:
```
[DEBUG] (2023-11-01 13:45:03.429) OptimizerGTSAM.cpp:615::optimize() GTSAM optimizing end (20 iterations done, error=370665897151686591118042194865150652730418506596897319548013708715507774486627007756496375995357581661849455872498980344507130287593126704789557833885327921244395869831168.000000 (initial=16453009441.994427 final=370665897151686591118042194865150652730418506596897319548013708715507774486627007756496375995357581661849455872498980344507130287593126704789557833885327921244395869831168.000000), time=0.002583 s)
[DEBUG] (2023-11-01 13:45:03.429) OptimizerGTSAM.cpp:675::optimize() Computing marginals...
[DEBUG] (2023-11-01 13:45:03.430) OptimizerGTSAM.cpp:679::optimize() Computed marginals = 0.000114s (key=1040)
[DEBUG] (2023-11-01 13:45:03.430) OptimizerGTSAM.cpp:725::optimize() Optimizing graph...end!
[DEBUG] (2023-11-01 13:45:03.430) Rtabmap.cpp:2967::process() Opt  -8 xyz=inf,inf,0.404141 rpy=0.085773,0.006991,-2.172289
[DEBUG] (2023-11-01 13:45:03.430) Rtabmap.cpp:2967::process() Opt  875 xyz=-inf,-inf,0.000000 rpy=0.000000,-0.000000,-0.380802
[DEBUG] (2023-11-01 13:45:03.430) Rtabmap.cpp:2967::process() Opt  876 xyz=inf,inf,0.000000 rpy=0.000000,0.000000,-2.488718
[DEBUG] (2023-11-01 13:45:03.430) Rtabmap.cpp:2967::process() Opt  1033 xyz=-inf,-inf,0.000000 rpy=0.000000,-0.000000,-1.994097
[DEBUG] (2023-11-01 13:45:03.430) Rtabmap.cpp:2967::process() Opt  1040 xyz=inf,-inf,0.000000 rpy=0.000000,0.000000,-0.070792
[ INFO] (2023-11-01 13:45:03.430) Rtabmap.cpp:2977::process() Compute max graph errors...
[DEBUG] (2023-11-01 13:45:03.430) Graph.cpp:909::computeMaxGraphErrors() poses=5 links=8
[ WARN] (2023-11-01 13:45:03.430) Graph.cpp:923::computeMaxGraphErrors() Poses are null or not invertible, aborting optimized graph max error check! (Pose 1040=xyz=inf,-inf,0.000000 rpy=0.000000,0.000000,-0.070792 Pose 875=xyz=-inf,-inf,0.000000 rpy=0.000000,-0.000000,-0.380802)
[FATAL] (2023-11-01 13:45:03.430) Transform.cpp:184::inverse() Condition (invertible) not met! [This transform is not invertible! xyz=inf,-inf,0.000000 rpy=0.000000,0.000000,-0.070792 
[0.997495 0.070733 0.000000 inf;
 -0.070733 0.997495 -0.000000 -inf;
 -0.000000 0.000000 1.000000 0.000000;
 0 0 0 1]]
```

I'm using ROS noetic, so the actual master branch is not compatible with the system I'm working on.
Then, I decided to change the solver used by the GTSAM from GaussNewton to Levenberg by switching the parameter:
```
GTSAM/Optimizer = "0"                               [0=Levenberg 1=GaussNewton 2=Dogleg]
```

As a result the Optimizer stopped crashing. It is rejecting the loop closures instead, as shown below:
```
[DEBUG] (2023-11-01 15:36:28.884) OptimizerGTSAM.cpp:615::optimize() GTSAM optimizing end (0 iterations done, error=10810002659.847393 (initial=10810002659.847393 final=10810002659.847393), time=0.000671 s)
[DEBUG] (2023-11-01 15:36:28.884) OptimizerGTSAM.cpp:675::optimize() Computing marginals...
[DEBUG] (2023-11-01 15:36:28.884) OptimizerGTSAM.cpp:679::optimize() Computed marginals = 0.000089s (key=1039)
[DEBUG] (2023-11-01 15:36:28.884) OptimizerGTSAM.cpp:725::optimize() Optimizing graph...end!
[DEBUG] (2023-11-01 15:36:28.884) Rtabmap.cpp:3081::process() Opt2  -8 xyz=0.851523,-0.041897,0.404141 rpy=0.085773,0.006991,1.561444
[DEBUG] (2023-11-01 15:36:28.884) Rtabmap.cpp:3081::process() Opt2  876 xyz=0.297985,-0.013632,0.000000 rpy=0.000000,0.000000,-0.039805
[DEBUG] (2023-11-01 15:36:28.884) Rtabmap.cpp:3081::process() Opt2  1039 xyz=-197.406799,29.594700,0.000000 rpy=0.000000,0.000000,-3.107898
[ INFO] (2023-11-01 15:36:28.884) Rtabmap.cpp:3091::process() Compute max graph errors...
[DEBUG] (2023-11-01 15:36:28.884) Graph.cpp:909::computeMaxGraphErrors() poses=3 links=4
[ INFO] (2023-11-01 15:36:28.884) Rtabmap.cpp:3112::process() Max optimization linear error = 196.587189 m (link 1039->876, var=0.000002, ratio error/std=144468.220376, thr=3.000000)
[ WARN] (2023-11-01 15:36:28.884) Rtabmap.cpp:3121::process() Rejecting localization (1039 <-> 876) in this iteration because a wrong loop closure has been detected after graph optimization, resulting in a maximum graph error ratio of 144468.218750 (edge 1039->876, type=1, abs error=196.587189 m, stddev=0.001361). The maximum error ratio parameter "RGBD/OptimizeMaxError" is 3.000000 of std deviation.
```

Do you have any thoughts about this behavior?
Thanks.

**Comment by matlabbe** [comment]
The master branch should work on Noetic (this is the main platform I am developing on). Otherwise, please report the compatibility issue. 

For:
```
[ WARN] (2023-11-01 13:45:03.430) Graph.cpp:923::computeMaxGraphErrors() Poses are null or not invertible, aborting optimized graph max error check! (Pose 1040=xyz=inf,-inf,0.000000 rpy=0.000000,0.000000,-0.070792 Pose 875=xyz=-inf,-inf,0.000000 rpy=0.000000,-0.000000,-0.380802)
[FATAL] (2023-11-01 13:45:03.430) Transform.cpp:184::inverse() Condition (invertible) not met! [This transform is not invertible! xyz=inf,-inf,0.000000 rpy=0.000000,0.000000,-0.070792 
[0.997495 0.070733 0.000000 inf;
 -0.070733 0.997495 -0.000000 -inf;
 -0.000000 0.000000 1.000000 0.000000;
 0 0 0 1]]
```
That update https://github.com/introlab/rtabmap/issues/1030 is also required. I'll suggest to use latest master branch in case there are other small commits depending on that. Remove rtabmap binaries and rebuild rtabmap and rtabmap_ros from [source](https://github.com/introlab/rtabmap_ros#build-from-source):
```
sudo apt remove ros-noetic-rtabmap*

cd ~
git clone https://github.com/introlab/rtabmap.git rtabmap
cd rtabmap/build
cmake ..
make -j6
sudo make install

cd ~/catkin_ws
git clone https://github.com/introlab/rtabmap_ros.git src/rtabmap_ros
catkin_make -j4
```

Otherwise, it seems GTSAM really doesn't like the constraints you are providing. In your case, do you have `Reg/Force3DoF=true`? The poses look 3DoF while the tags are 6DoF. Are the tags detected with external node? Normally, rtabmap should handle 6DoF tag constraints even in 3DoF optimization mode. You could try with `Reg/Force3DoF=false` just to compare though.

**Comment by matlabbe** [comment]
Just confirming that even if odometry pose is large, GTSAM should be able to converge correctly. Here I reset odometry to x=10000 and y=8000:
```
[ INFO] (2023-11-01 14:31:20.381) Rtabmap.cpp:2979::process() timeAddLoopClosureLink=0.000003s
[DEBUG] (2023-11-01 14:31:20.381) Rtabmap.cpp:3055::process() RGB-D SLAM mode: 1
[DEBUG] (2023-11-01 14:31:20.381) Rtabmap.cpp:3056::process() Incremental: 0
[DEBUG] (2023-11-01 14:31:20.381) Rtabmap.cpp:3057::process() Loop hyp: 9
[DEBUG] (2023-11-01 14:31:20.381) Rtabmap.cpp:3058::process() Last prox: 9
[DEBUG] (2023-11-01 14:31:20.381) Rtabmap.cpp:3059::process() Reduced ids: 0
[DEBUG] (2023-11-01 14:31:20.381) Rtabmap.cpp:3060::process() Has prior: 0 (prior ignored=1)
[DEBUG] (2023-11-01 14:31:20.381) Rtabmap.cpp:3061::process() Has gravity: 1 (sigma=0.300000, odomGravity=0, refined=0)
[DEBUG] (2023-11-01 14:31:20.381) Rtabmap.cpp:3062::process() Has virtual link: 0
[DEBUG] (2023-11-01 14:31:20.381) Rtabmap.cpp:3063::process() Prox Time: 0
[DEBUG] (2023-11-01 14:31:20.381) Rtabmap.cpp:3064::process() Landmarks: 0
[DEBUG] (2023-11-01 14:31:20.381) Rtabmap.cpp:3065::process() Retrieved: 0
[DEBUG] (2023-11-01 14:31:20.381) Rtabmap.cpp:3066::process() Not self ref links: 1
[DEBUG] (2023-11-01 14:31:20.381) Rtabmap.cpp:3150::process() Constraint 184->184 (type=Gravity, var = 1.000000 1.000000)
[DEBUG] (2023-11-01 14:31:20.381) Rtabmap.cpp:3148::process() Constraint 9->9 (type=PosePrior)
[DEBUG] (2023-11-01 14:31:20.381) Rtabmap.cpp:3150::process() Constraint 184->9 (type=GlobalClosure, var = 0.000223 0.003220)
[DEBUG] (2023-11-01 14:31:20.381) Rtabmap.cpp:3154::process() Pose 9 xyz=-0.291190,-0.002876,-0.033898 rpy=0.183713,0.389845,-2.646930
[DEBUG] (2023-11-01 14:31:20.381) Rtabmap.cpp:3154::process() Pose 184 xyz=10000.000000,8000.000000,0.000000 rpy=0.177814,0.359494,-2.979261
[DEBUG] (2023-11-01 14:31:20.381) Rtabmap.cpp:3161::process() priorsIgnored was true
[DEBUG] (2023-11-01 14:31:20.381) Optimizer.cpp:196::getConnectedGraph() IN: fromId=184 poses=2 links=3 priorsIgnored=0 landmarksIgnored=0
[DEBUG] (2023-11-01 14:31:20.381) Optimizer.cpp:301::getConnectedGraph() OUT: poses=2 links=3
[DEBUG] (2023-11-01 14:31:20.381) OptimizerGTSAM.cpp:101::optimize() Optimizing graph...
[DEBUG] (2023-11-01 14:31:20.381) OptimizerGTSAM.cpp:163::optimize() fill poses to gtsam... rootId=0 (priorsIgnored=0 landmarksIgnored=0)
[DEBUG] (2023-11-01 14:31:20.381) OptimizerGTSAM.cpp:223::optimize() fill edges to gtsam...
[DEBUG] (2023-11-01 14:31:20.381) OptimizerGTSAM.cpp:495::optimize() create optimizer
[DEBUG] (2023-11-01 14:31:20.381) OptimizerGTSAM.cpp:520::optimize() GTSAM optimizing begin (max iterations=20, robust=0)
[DEBUG] (2023-11-01 14:31:20.382) OptimizerGTSAM.cpp:604::optimize() iteration 1 error =3529.759225
[DEBUG] (2023-11-01 14:31:20.382) OptimizerGTSAM.cpp:604::optimize() iteration 2 error =0.318584
[DEBUG] (2023-11-01 14:31:20.382) OptimizerGTSAM.cpp:604::optimize() iteration 3 error =0.271166
[DEBUG] (2023-11-01 14:31:20.382) OptimizerGTSAM.cpp:604::optimize() iteration 4 error =0.271165
[DEBUG] (2023-11-01 14:31:20.382) OptimizerGTSAM.cpp:614::optimize() Stop optimizing, not enough improvement (0.000001 < 0.000010)
[DEBUG] (2023-11-01 14:31:20.382) OptimizerGTSAM.cpp:633::optimize() GTSAM optimizing end (4 iterations done, error=0.271165 (initial=84492982519949.375000 final=0.271165), time=0.000274 s)
[DEBUG] (2023-11-01 14:31:20.382) OptimizerGTSAM.cpp:697::optimize() Computing marginals...
[DEBUG] (2023-11-01 14:31:20.382) OptimizerGTSAM.cpp:701::optimize() Computed marginals = 0.000040s (key=184)
[DEBUG] (2023-11-01 14:31:20.382) OptimizerGTSAM.cpp:750::optimize() Optimizing graph...end!
[DEBUG] (2023-11-01 14:31:20.382) Rtabmap.cpp:3170::process() Opt  9 xyz=-0.291190,-0.002876,-0.033898 rpy=0.183711,0.389845,-2.646930
[DEBUG] (2023-11-01 14:31:20.382) Rtabmap.cpp:3170::process() Opt  184 xyz=-0.217603,0.092621,-0.115117 rpy=0.218768,0.354219,-2.363997
[ INFO] (2023-11-01 14:31:20.382) Rtabmap.cpp:3180::process() Compute max graph errors...
```
Maybe the tag detection is too wrong to correctly converge.

**Comment by matlabbe** [comment]
I updated the code with a change for landmark constraints in localization mode that could help with your issue. You may give a try. If the issue is still there, you may increase this new parameter called `RGBD/LocalizationPriorError` to `0.01` or `0.1`.

**Comment by ApoloM** [comment]
Thanks for the update. 

Apparently the landmark constraints are the problem. 
By using the ```Reg/Force3DoF=false``` and ```GTSAM/Optimizer=0``` I could supress the warnings and crashes.
 
I'm not using an external node to detect the apriltags.

I will try the suggested version and parameters.

Thanks again.

**Comment by matlabbe** [comment]
I will try to reproduce the issue that this commit was fixing, I don't remember on top of my head what was the issue addressed there. In your case, if I understand, if you change this line by:
```cpp
_graphOptimizer->getConnectedGraph(signature->id(), poses, constraints, posesOut, edgeConstraintsOut);
```
Would it fix your issue?

**Comment by ApoloM** [comment]
Yes, it would fix my issue.

**Comment by matlabbe** [comment]
I removed the last argument of that function and simplified the code. I think I reproduced the issue of switching from a map created with `Reg/Force3DoF=true`, then try to localize with `Reg/Force3DoF=false`, this make the robot flips upside down. It is because the tags were transformed for 3DoF optimization, which is not the real pose for 6DoF. Here are two examples of the same tag when mapping with `Reg/Force3DoF=true` and `Reg/Force3DoF=false` respectively (the real orientation is the second one, with z axis perpendicular to the tag):
![Screenshot from 2023-11-15 22-35-49](https://github.com/introlab/rtabmap_ros/assets/2319645/0097183a-c110-4153-baa9-ad6490dbac1f)
![Screenshot from 2023-11-15 22-37-04](https://github.com/introlab/rtabmap_ros/assets/2319645/18a3dcb6-ab52-4023-b7c3-f00598859230)

To make 2D optimization working, as it optimizes only x,y, and yaw, the orientation of the tag should have z-axis up. The bug is that after optimization, we don't flip back the correct orientation of the tag, so if we switch to 6DoF in localization, the robot will think the tag is flipped 90 deg. I need to dig more into this in the next days.

**Comment by matlabbe** [comment]
There is the [code](https://github.com/introlab/rtabmap/commit/bca8b30832a3e8e75185e2b73a75fca699eb674b) flipping the tag pose with `Reg/Force3DoF=true`: 
```
if(_registrationPipeline->force3DoF())
{
	// For 2D slam, make sure the landmark z axis is up
	rtabmap::Transform tx = landmarkPose.rotation() * rtabmap::Transform(1,0,0,0,0,0);
	rtabmap::Transform ty = landmarkPose.rotation() * rtabmap::Transform(0,1,0,0,0,0);
	if(fabs(tx.z()) > 0.9)
	{
		landmarkPose*=rtabmap::Transform(0,0,0,0,(tx.z()>0?1:-1)*M_PI/2,0);
	}
	else if(fabs(ty.z()) > 0.9)
	{
		landmarkPose*=rtabmap::Transform(0,0,0,(ty.z()>0?-1:1)*M_PI/2,0,0);
	}
}
```
Well, this works well if we don't change `Reg/Force3DoF` over time (from 3DoF to 6doF or vice-versa). 

Another note, could you also show the covairance set in your odometry topic (assuming it is called `/odom`)?
```
rostopic echo /odom
```
I saw some GTSAM indeterminant error while testing on the simulator and it was caused by bad covariance.

**Comment by ApoloM** [comment]
> There is the [code](https://github.com/introlab/rtabmap/commit/bca8b30832a3e8e75185e2b73a75fca699eb674b) flipping the tag pose with `Reg/Force3DoF=true`:
> 
> ```
> if(_registrationPipeline->force3DoF())
> {
> 	// For 2D slam, make sure the landmark z axis is up
> 	rtabmap::Transform tx = landmarkPose.rotation() * rtabmap::Transform(1,0,0,0,0,0);
> 	rtabmap::Transform ty = landmarkPose.rotation() * rtabmap::Transform(0,1,0,0,0,0);
> 	if(fabs(tx.z()) > 0.9)
> 	{
> 		landmarkPose*=rtabmap::Transform(0,0,0,0,(tx.z()>0?1:-1)*M_PI/2,0);
> 	}
> 	else if(fabs(ty.z()) > 0.9)
> 	{
> 		landmarkPose*=rtabmap::Transform(0,0,0,(ty.z()>0?-1:1)*M_PI/2,0,0);
> 	}
> }
> ```
> 
> Well, this works well if we don't change `Reg/Force3DoF` over time (from 3DoF to 6doF or vice-versa). I'll check to make it work when changing the parameter.
> 
> Another note, could you also show the covairance set in your odometry topic (assuming it is called `/odom`)?
> 
> ```
> rostopic echo /odom
> ```
> 
> I saw some GTSAM indeterminant error while testing on the simulator and it was caused by bad covariance.

Here is the odometry data at the instant in which the fatal error crashes the system:
```
---
header: 
  seq: 70391
  stamp: 
    secs: 1698255109
    nsecs: 269333124
  frame_id: "odom"
child_frame_id: "base_link"
pose: 
  pose: 
    position: 
      x: -197.40680530411618
      y: 29.594699332749887
      z: 0.0
    orientation: 
      x: 0.0
      y: 0.0
      z: -0.9998580829759275
      w: 0.01684677736848209
  covariance: [0.2457867145028996, 0.007579704226761971, 0.0, 0.0, 0.0, 0.0, 0.007579704226762059, 0.024866542874265603, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 5.7500875447710605e-09, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 5.750072786080242e-09, 6.512993045552662e-47, 0.0, 0.0, 0.0, 0.0, -6.512993045552662e-47, 5.750072786080242e-09, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 8.166713637045317e-05]
twist: 
  twist: 
    linear: 
      x: 0.0
      y: 0.0
      z: 0.0
    angular: 
      x: 0.0
      y: 0.0
      z: 3.259415738863996e-27
  covariance: [0.006402685183589715, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0006488214186150694, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.2140061976883634e-06, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.2140058844170501e-06, -7.278402106173485e-51, 0.0, 0.0, 0.0, 0.0, 7.278402177381913e-51, 1.2140058844170501e-06, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.004041672752928651]
```

**Comment by matlabbe** [comment]
The odometry topic covariance looks fine, but if you are using `odom_frame_id`, those [parameters](http://wiki.ros.org/rtabmap_slam) are used:

> ~odom_tf_linear_variance (double, default: 0.001)
>     When odom_frame_id is used, the first 3 values of the diagonal of the 6x6 covariance matrix are set to this value. 
> 
> ~odom_tf_angular_variance (double, default: 0.001)
>     When odom_frame_id is used, the last 3 values of the diagonal of the 6x6 covariance matrix are set to this value. 

which should not cause that issue with those default values.

In the commit above, I updated the code to remove the last argument of `getConnectedGraph()` so this would fix the current issue. I won't "fix" the problem of switching `Reg/Force3DoF` from true to false or vice-versa when the map contains landmarks, as the changes would be quite deep to do and I think the current code is more efficient in its current state. If you already tested

**Comment by ApoloM** [comment]
Hi, I have some updates again.

I made the tests with the commit above and finally the issue was solved. 
The system is working perfectly and everything is great.

Thanks for the help and explanations about this awesome tool.
